### PR TITLE
Update kevago usage

### PR DESCRIPTION
**Pull request by tuhuynh27**
Can use this command to test install at this branch:

```
go get github.com/tuhuynh27/keva/go-client@132474d09e43ad9de74d2318bb5045a63e34209c
```

Example repo https://github.com/tuhuynh27/kevago-example

### CODE REVIEW

**Comment by tuhuynh27** [comment]
@duongcongtoai I updated & try the example, this feels a little uncomfortable when importing isn't it?

```golang
import (
    "context"
    "fmt"
    _ "github.com/tuhuynh27/keva/go-client"
    kevago "github.com/tuhuynh27/keva/go-client"
    "github.com/tuhuynh27/keva/go-client/pool"
    "net"
    "time"
)

func ExampleClient() {
	poolOpts := pool.Options{
		PoolTimeout: time.Second, // max time to wait to get new connection from pool
		PoolSize:    20, // max number of connection can get from the pool
		MinIdleConn: 5,
		Dialer: func(ctx context.Context) (net.Conn, error) { //Must define dialer func
			conn, err := net.Dial("tcp", "localhost:6767")
			if err != nil {
				return nil, err
			}
			return conn, err
		},
		IdleTimeout:        time.Minute * 5, // if connection lives longer than 5 minutes, it is removable
		MaxConnAge:         time.Minute * 10, // all connections cannot live longer than this
		IdleCheckFrequency: time.Minute * 5, // reap staled connections after 5 minutes
	}

	var ret string
	client, _ := kevago.NewClient(kevago.Config{
		Pool: poolOpts,
	})
	ret, _ = client.Set("key1", "value1")
	fmt.Println(ret)
	ret, _ = client.Get("key1")
	fmt.Println(ret)
}
```

`kevago "github.com/tuhuynh27/keva/go-client"`
`poolOpts := pool.Options`
`client, _ := kevago.NewClient`

I think we should better use just one namespace for those

**Comment by tuhuynh27** [comment]
@duongcongtoai  And maybe should we also add a default NewClient constructor (with zero arg)?

Like this:

```golang
client, _ := kevago.NewDefaultClient()
	ret, _ = client.Set("key1", "value1")
	fmt.Println(ret)
	ret, _ = client.Get("key1")
	fmt.Println(ret)
}
```

**Comment by duongcongtoai** [comment]
> @duongcongtoai I updated & try the example, this feels a little uncomfortable when importing isn't it?

We can actually import directly without the "kevago" package alias, and directly call it inside the code with the name kevago itself. I think your IDE automatically add the word kevago before the import path.
But yeah, it looks hard to trace the package name. We can just rename it to goclient, the import path provides enough context that it is a client for keva.


> I think we should better use just one namespace for those
I added the default function for convenient.

**Comment by tuhuynh27** [comment]
Great thanks @duongcongtoai

**Pull request closed without merging**
