### PR TITLE
Use Netty and deprecate old NIO server

### PR DESCRIPTION
**Pull request by axblueblader**
- Add minimal netty dependencies
- Implement netty server
- Refactor tests
- Remove old servers

### CODE REVIEW

**Comment by tuhuynh27** [comment]
@axblueblader Can we consider use Redis Codec? Is it easy to apply

**Comment by axblueblader** [comment]
> @axblueblader Can we consider use Redis Codec? Is it easy to apply

Yes but I think in the next PR

With Netty, parsing the Redis command from server should be easy, but how we map Redis to our own capabilities might require more thoughts and refactor like we will have a mapping to convert a Redis command 1-1 to our command, or we need to split the logic between how a command uses the store for different protocol, or do we convert to using Redis protocol entirely?

**Comment by tuhuynh27** [comment]
@axblueblader To use Redis protocol, we have to convert to using Redis protocol for all operations, start with the existed operations like GET, PUT, EXPIRE
It might take extra time to redesign so okay better it would be in the next PR

**Comment by tuhuynh27** [comment]
Also, can you consider removing all old BIO/NIO servers to reduce the code complexity?

**Review by tuhuynh27 — APPROVED** [review]
LGTM

**Review by tuhuynh27 — APPROVED** [review]

**Pull request merged**
